
package edu.esprit;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import edu.esprit.locator.EmailValidator;
import edu.esprit.locator.Locator;
import edu.letechno.entity.User;
import edu.letechno.session.IUserSession;

public class addMember extends javax.swing.JFrame {

	/**
	 * Creates new form addMember
	 */
	public addMember(User usr) {

		initComponents();
		ImageIcon icon = new ImageIcon("src/main/resources/favicon.png");
		this.setVisible(true);
		this.setResizable(false);
		this.setIconImage(icon.getImage());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		b = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		a = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		c = new javax.swing.JTextField();
		d = new javax.swing.JTextField();
		e = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		b.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Nom : ");

		jLabel2.setText("Password :");

		jLabel3.setText("Login :");

		jLabel4.setText("Mail :");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel5.setIcon(new javax.swing.ImageIcon("src/main/resources/plus_button_symbol_400_clr_6175.png")); // NOI18N
		jLabel5.setText("Add Member");
		jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jLabel5MouseClicked(evt);
				} catch (Exception e) {
					System.out.println(e.getMessage());
				}
			}
		});

		e.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		e.setForeground(new java.awt.Color(255, 51, 0));

		javax.swing.GroupLayout bLayout = new javax.swing.GroupLayout(b);
		b.setLayout(bLayout);
		bLayout.setHorizontalGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bLayout.createSequentialGroup().addGroup(bLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(bLayout.createSequentialGroup().addGap(31, 31, 31)
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(bLayout.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												bLayout.createSequentialGroup().addComponent(jLabel1).addGap(33, 33, 33)
														.addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGroup(bLayout.createSequentialGroup()
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(bLayout.createSequentialGroup().addGap(31, 31, 31)
												.addComponent(jLabel4).addGap(38, 38, 38))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										bLayout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
												.addGap(18, 18, 18)))
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(bLayout.createSequentialGroup().addContainerGap().addComponent(e,
										javax.swing.GroupLayout.PREFERRED_SIZE, 148,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										bLayout.createSequentialGroup().addGap(78, 78, 78).addComponent(jLabel5,
												javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(65, Short.MAX_VALUE)));
		bLayout.setVerticalGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bLayout.createSequentialGroup()
						.addGroup(bLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										bLayout.createSequentialGroup().addGap(91, 91, 91)
												.addGroup(bLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1).addComponent(a,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(20, 20, 20)
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(28, 28, 28)
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2).addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(bLayout.createSequentialGroup().addGap(232, 232, 232)
								.addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
				.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(61, 61, 61)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(b,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(b,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		setSize(new java.awt.Dimension(356, 546));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) throws Exception {
		String response = null;
		if (validator.validate(d.getText())) {
			IUserSession user = (IUserSession) Locator.lookup("UserSession", IUserSession.class);

			User newuser = new User(a.getText(), " ", jTextField8.getText(), d.getText(), validator.md5(c.getText()),
					"committee");
			response = user.CreateUser(newuser);
			if (response.equals("success")) {
				this.dispose();
				// new Commitee(loggeduser).setVisible(true);
			} else {
				JOptionPane.showMessageDialog(null, response);
			}
		} else {
			JOptionPane.showMessageDialog(null, "Invalid email Adress form");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				User usss = new User("nader", "nader", "nader", "nader", "nader", "nader");
				new addMember(usss).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField a;
	private javax.swing.JPanel b;
	private javax.swing.JTextField c;
	private javax.swing.JTextField d;
	private javax.swing.JLabel e;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField jTextField8;
	private User loggeduser;
	private EmailValidator validator = new EmailValidator();;
	// End of variables declaration
}
