package edu.esprit;

import java.awt.event.ActionListener;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import edu.esprit.locator.EmailValidator;
import edu.esprit.locator.Locator;
import edu.letechno.entity.User;
import edu.letechno.session.IUserSession;
import javafx.event.ActionEvent;

public class AuthentificationFinaL extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AuthentificationFinaL() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/favicon.png");
    	this.setVisible(true);this.setResizable(false);
    	this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        c = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 527));
        getContentPane().setLayout(null);

        c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(c);
        c.setBounds(70, 390, 180, 0);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forget your Password ? ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 480, 140, 20);

        jButton1.setIcon(new javax.swing.ImageIcon("src/main/resources/sig.png")); // NOI18N
       jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 430, 120, 30);
        getContentPane().add(b);
        b.setBounds(60, 340, 200, 30);
        getContentPane().add(a);
        a.setBounds(60, 290, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("src/main/resources/letechno.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 290, 520);

        setSize(new java.awt.Dimension(290, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
     try{	
    	 	IUserSession user =(IUserSession) Locator.lookup("UserSession", IUserSession.class);
	        User loggeduser = user.login(a.getText(), validator.md5(b.getText()));
	       
	        if(loggeduser == null){
	            JOptionPane.showMessageDialog(null, "Invalid password/username combination");
	        }else if(!loggeduser.getRole().equals("admin")) {
	        			JOptionPane.showMessageDialog(null, "Sorry, you can't log in to this application");
	        	   }else{
	        	this.dispose();
	            new SpaceAdmin(loggeduser).setVisible(true);
	        }
        }catch(Exception e){
        	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }  
     
     
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.dispose();
        new ForgetPassword().setVisible(true);
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationFinaL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationFinaL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationFinaL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationFinaL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	AuthentificationFinaL x =  new AuthentificationFinaL();
            	// iconURL is null when not found
            	
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JLabel c;
    static private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private EmailValidator validator= new EmailValidator();
    // End of variables declaration                   
}
